In [12]:
import pyspark
from pyspark import SQLContext
from pyspark.sql.window import Window
import pyspark.sql.functions as F
import pyspark.sql.types as Types
sc = SparkContext.getOrCreate();
sql = SQLContext(sc)

citiesPopDf = (sql.read
         .format("com.databricks.spark.csv")
         .option("header", "true")
         .load("world_population/worldcities.csv"))\
         .withColumn("city_population", F.col("Population").cast("float"))\
         .where(F.col("city_population").cast("int") > 0)

citiesIthRanksDf = citiesPopDf\
  .withColumn("rank", \
    F.rank().over(Window.partitionBy("country")\
    .orderBy(F.col("city_population").desc())))

citiesIthRanksDf\
.sort(F.col("city_population").desc())\
.where(F.col('rank') == 1)\
.select(["city", "country", "city_population"])\
.limit(10)\
.show()

"""
+------------+-------------+---------------+
|        city|      country|city_population|
+------------+-------------+---------------+
|       Tokyo|        Japan|       3.5676E7|
|    New York|United States|    1.9354922E7|
| Mexico City|       Mexico|       1.9028E7|
|      Mumbai|        India|       1.8978E7|
|   São Paulo|       Brazil|       1.8845E7|
|    Shanghai|        China|       1.4987E7|
|       Dhaka|   Bangladesh|    1.2797394E7|
|Buenos Aires|    Argentina|       1.2795E7|
|     Karachi|     Pakistan|        1.213E7|
|       Cairo|        Egypt|       1.1893E7|
+------------+-------------+---------------+
"""

citiesIthRanksDf\
.sort(F.col("city_population").desc())\
.where(F.col('rank') == 2)\
.select(["city", "country", "city_population"])\
.limit(10)\
.show()

"""
+----------------+-------------+---------------+
|            city|      country|city_population|
+----------------+-------------+---------------+
|           Delhi|        India|       1.5926E7|
|     Los Angeles|United States|    1.2815475E7|
|  Rio de Janeiro|       Brazil|       1.1748E7|
|           Ōsaka|        Japan|       1.1294E7|
|         Beijing|        China|       1.1106E7|
|          Lahore|     Pakistan|      6577000.0|
|       Barcelona|        Spain|      4920000.0|
|Saint Petersburg|       Russia|      4553000.0|
|      Chittagong|   Bangladesh|      4529000.0|
|           Hanoi|      Vietnam|      4378000.0|
+----------------+-------------+---------------+
"""

+------------+-------------+---------------+
|        city|      country|city_population|
+------------+-------------+---------------+
|       Tokyo|        Japan|       3.5676E7|
|    New York|United States|    1.9354922E7|
| Mexico City|       Mexico|       1.9028E7|
|      Mumbai|        India|       1.8978E7|
|   São Paulo|       Brazil|       1.8845E7|
|    Shanghai|        China|       1.4987E7|
|       Dhaka|   Bangladesh|    1.2797394E7|
|Buenos Aires|    Argentina|       1.2795E7|
|     Karachi|     Pakistan|        1.213E7|
|       Cairo|        Egypt|       1.1893E7|
+------------+-------------+---------------+

+----------------+-------------+---------------+
|            city|      country|city_population|
+----------------+-------------+---------------+
|           Delhi|        India|       1.5926E7|
|     Los Angeles|United States|    1.2815475E7|
|  Rio de Janeiro|       Brazil|       1.1748E7|
|           Ōsaka|        Japan|       1.1294E7|
|         Beijing|        China|       1.1106E7|
|          Lahore|     Pakistan|      6577000.0|
|       Barcelona|        Spain|      4920000.0|
|Saint Petersburg|       Russia|      4553000.0|
|      Chittagong|   Bangladesh|      4529000.0|
|           Hanoi|      Vietnam|      4378000.0|
+----------------+-------------+---------------+